FROM python:3.8

SHELL ["/bin/bash", "-c"]

# Import requirement file first and install required packages
WORKDIR /tmp
COPY python/requirements.txt .
COPY python/itl/memory/requirements.txt itl/memory/
COPY python/itl/vision/requirements.txt itl/vision/
COPY python/itl/lang/requirements.txt itl/lang/
COPY python/itl/symbolic_reasoning/requirements.txt itl/symbolic_reasoning/
COPY python/itl/practical_reasoning/requirements.txt itl/practical_reasoning/
COPY python/itl/lpmln/requirements.txt itl/lpmln/
RUN pip install --no-cache-dir pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir gdown

# Needed to import cv2
RUN apt update && apt install -y libgl1

# Let's add in vim
RUN apt install -y vim

# Install virtual display buffer X server and X11 server utils
RUN apt install -y xvfb
RUN apt install -y x11-xserver-utils

# Create a non-root user
RUN useradd --create-home nonroot

# Import the repository content
RUN mkdir /home/nonroot/ns-arch-unity
WORKDIR /home/nonroot/ns-arch-unity
COPY . .
RUN chown -R nonroot .

# Login as non-root
USER nonroot

# Display env var
ENV DISPLAY :99

ENTRYPOINT ["/bin/bash", "tools/container_scripts/eval_with_xvfb.sh"]
